### ISSUE TITLE
Error When Fetching Data

### ISSUE THREAD

**Issue by waqary705** [kaelaela/OpenGraphView#2]
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
                                                                       Process: com.app.footballstars, PID: 30323
                                                                       java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                           at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                           at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: java.lang.StringIndexOutOfBoundsException: length=7; regionStart=0; regionLength=18
                                                                           at java.lang.String.startEndAndLength(String.java:504)
                                                                           at java.lang.String.substring(String.java:1333)
                                                                           at com.bilytica.mygraphlibarary.OGParser.parse(OGParser.java:46)
                                                                           at com.bilytica.mygraphlibarary.network.tasks.LoadOGDataTask.doInBackground(LoadOGDataTask.java:51)
                                                                           at com.bilytica.mygraphlibarary.network.tasks.LoadOGDataTask.doInBackground(LoadOGDataTask.java:14)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:292)

**Comment by kaelaela** [comment]
Hi, @waqary705 .
Thx your issue. Please tell me your testing url.

**Comment by billionbucks** [comment]
so what we can do for handling this Exception?

**Comment by billionbucks** [comment]
how can i use your new updated version of this library? cause i'm still having this error but it seems like you recently fixed it
